// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RFLOT.Domain.Report.ValueObjects;
using RFLOT.Infrastructure.Report;

#nullable disable

namespace RFLOT.Infrastructure.Report.Migrations
{
    [DbContext(typeof(ReportDbContext))]
    [Migration("20240512175004_GuidToString")]
    partial class GuidToString
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RFLOT.Domain.Report.Report", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DateTimeFinish")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("DateTimeStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IdPlane")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("StatusReport")
                        .HasColumnType("boolean");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<IEnumerable<ZoneReport>>("ZoneReports")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.ToTable("Reports");
                });
#pragma warning restore 612, 618
        }
    }
}
