services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_DB: "rfid"
      POSTGRES_USER: "rfid"
      POSTGRES_PASSWORD: "rfid"
    volumes:
      - ./db-data:/var/lib/postgresql/data
      - ./init-data:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "postgres"
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
volumes:
  postgres:
  pgadmin:
